- TPSI/lavalle_marco/lavalle_es_html_01.html
Buonasera professore, le consegno la repository con l'esercitazione 1 di HTML di TPSI
(Ho fatto un po' di commit per correggere errori)
La Valle Marco
> Le consegno il file lavalle_es_html_01.html

- RETI/bianchi_emanuele/bianchi_es_01.html
buona sera, le invio l'esercitazione iniziata in classe su html
> esercitazione 1 html

- TPSI/ruscica_lorenzo/ruscica_es_html_01.html
buongiorno prof, ho lasciato le directory dei compagni come detto da lei, aggiungendo solo i miei file
> Riconsenga file html

- TPSI/pezzana_simone/html/pezzana_es_html_01.html
- TPSI/pezzana_simone/html/pezzana_es_html_02.html
- TPSI/pezzana_simone/html/pezzana_es_html_03.html
Consegna dell'esercitazioni 1,2,3 di html
> Consegna delle esercitazioni 1,2,3

- TPSI/bianchi_emanuele/html/bianchi_es_html_01.html
- TPSI/bianchi_emanuele/html/bianchi_esercizio_html_02.html
- TPSI/bianchi_emanuele/html/bianchi_esercizio_html_03.html
le invio l'esercitazione 1 che avevo sbagliato a consegnare; le invio inoltre le esercitazioni 2 e 3 che abbiamo fatto in classe e terminato a casa.
buona serata
> esercitazioni html (1,2,3)

- TPSI/bianchi_emanuele/html/bianchi_esercizio_html_09.html
- TPSI/bianchi_emanuele/html/bianchi_esercizio_html_10.html
- TPSI/bianchi_emanuele/html/bianchi_esercizio_html_11.html
esercitazioni eseguite in classe il 27/11/2024
> Esercitazioni 09 & 10 di html

- TPSI/correndo_marco/html/correndo_es_html_09.html
- TPSI/correndo_marco/html/correndo_es_html_10.html
- TPSI/correndo_marco/html/correndo_es_html_11.html
Consegna delle esercitazioni 9,10,11 html
> Consegna dell'esercitazione 9,10,11 html

- TPSI/prevedi_daniele/Esercitazioni_HTML/prevedi_esercizio_html_12.html
- TPSI/prevedi_daniele/Esercitazioni_HTML/prevedi_esercizio_html_13.html
Buongiorno,
consegno l'esercitazione HTML 12 e 13 di TPSI
Cordiali saluti,
Prevedi Daniele
> (Prevedi) Consegna Esercitazione 12,13 TPSI

- TPSI/pezzana_simone/html/pezzana_es_html_12.html
- TPSI/pezzana_simone/html/pezzana_es_html_14.html
consegno dell' esercitazione 12 html.
> commit dell' esercitazione 12 html.

- TPSI/bianchi_emanuele/html/bianchi_esercizio_html_12.html
> bianchi_esercizio_html_12.html

- TPSI/correndo_marco/html/correndo_esercizio_html_16.html
- TPSI/correndo_marco/html/correndo_esercizio_html_17.html
Consegna esercitazioni 16 e 17 di html
> Consegna esercitazioni 16,17 html

- TPSI/prevedi_daniele/Esercitazioni_CSS/htmls/prevedi_esercizio_css_01.html
- TPSI/prevedi_daniele/Esercitazioni_CSS/htmls/prevedi_esercizio_css_02.html
- TPSI/prevedi_daniele/Esercitazioni_CSS/htmls/prevedi_esercizio_css_03.html
- TPSI/prevedi_daniele/Esercitazioni_CSS/htmls/prevedi_esercizio_css_04.html
- TPSI/prevedi_daniele/Esercitazioni_CSS/styles/prevedi_esercizio_css_03.css
- TPSI/prevedi_daniele/Esercitazioni_CSS/styles/prevedi_esercizio_css_04.css
Buongiorno,
Consegno le esercitazioni CSS 1, 2, 3, 4.
Cordiali saluti,
Prevedi Daniele
> (Prevedi) Consegna Esercitazioni 1, 2, 3, 4 CSS

- TPSI/correndo_marco/css/correndo_esercizio_css_01.html
- TPSI/correndo_marco/css/correndo_esercizio_css_02.html
- TPSI/correndo_marco/css/correndo_esercizio_css_03.css
- TPSI/correndo_marco/css/correndo_esercizio_css_03.html
- TPSI/correndo_marco/css/correndo_esercizio_css_04.css
- TPSI/correndo_marco/css/correndo_esercizio_css_04.html
- TPSI/correndo_marco/html/correndo_es_galleria1.html
- TPSI/correndo_marco/html/correndo_es_galleria2.html
- TPSI/correndo_marco/html/correndo_es_skeleton_page.html
- TPSI/correndo_marco/html/correndo_esercizio_html_17.html
Consegna della galleria1, galleria2 e skeleton page
> Consegna delle esercitazioni del 15/01

- TPSI/correndo_marco/css/correndo_esercizio_css_05.css
- TPSI/correndo_marco/css/correndo_esercizio_css_05.html
- TPSI/correndo_marco/css/correndo_esercizio_css_06.css
- TPSI/correndo_marco/css/correndo_esercizio_css_06.html
> Consegna es css 05 e 06

- TPSI/prevedi_daniele/Esercitazioni_CSS/htmls/prevedi_esercizio_css_05.html
- TPSI/prevedi_daniele/Esercitazioni_CSS/htmls/prevedi_esercizio_css_06.html
- TPSI/prevedi_daniele/Esercitazioni_CSS/styles/prevedi_esercizio_css_05.css
- TPSI/prevedi_daniele/Esercitazioni_CSS/styles/prevedi_esercizio_css_06.css
Buongiorno, 
Consegno le esercitazioni odierne numero 5 e 6 di CSS.
Cordiali saluti,
Prevedi Daniele
> (Prevedi) Consegna Esercitazioni 5, 6 CSS

- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_07.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_07.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_08.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_08.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_10.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_10.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_11.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_11.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_12.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_12.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_13.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_13.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_14.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_14.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_15.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_15.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_16.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_16.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_17.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_17.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_18.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_18.html
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_19.css
- TPSI/bianchi_emanuele/css/bianchi_esercizio_css_19.html
ecco le esercitazioni dalla 7 alla 11 eseguite in classe di CSS
> Esercitazioni 7,8,9,10,11,12,13,14,15,16,17,18,19

- TPSI/correndo_marco/css/correndo_esercizio_css_24.css
- TPSI/correndo_marco/css/correndo_esercizio_css_28.html
- TPSI/correndo_marco/css/correndo_esercizio_css_29.css
- TPSI/correndo_marco/css/correndo_esercizio_css_29.html
- TPSI/correndo_marco/css/correndo_esercizio_css_30.css
- TPSI/correndo_marco/css/correndo_esercizio_css_30.html
- TPSI/correndo_marco/css/correndo_esercizio_css_31.css
- TPSI/correndo_marco/css/correndo_esercizio_css_31.html
- TPSI/correndo_marco/css/correndo_esercizio_css_32.css
- TPSI/correndo_marco/css/correndo_esercizio_css_32.html
- TPSI/correndo_marco/css/correndo_esercizio_css_33.css
- TPSI/correndo_marco/css/correndo_esercizio_css_33.html
- TPSI/correndo_marco/css/correndo_esercizio_css_34.css
- TPSI/correndo_marco/css/correndo_esercizio_css_34.html
Consegna delle esercitazioni di TPSI css da 28 a 34
> Consegna esercitazioni css da 28 a 34

- TPSI/correndo_marco/css/correndo_esercizio_css_35.css
- TPSI/correndo_marco/css/correndo_esercizio_css_35.html
- TPSI/correndo_marco/css/correndo_esercizio_css_36.css
- TPSI/correndo_marco/css/correndo_esercizio_css_36.html
- TPSI/correndo_marco/css/correndo_esercizio_css_37.css
- TPSI/correndo_marco/css/correndo_esercizio_css_37.html
Consegna esercitazioni di tpsi css 35 36 e 37
> Consegna esercitazioni css da 35 a 37

- TPSI/correndo_marco/css/correndo_esercizio_css_39.css
- TPSI/correndo_marco/css/correndo_esercizio_css_39.html
- TPSI/correndo_marco/css/correndo_esercizio_css_40.css
- TPSI/correndo_marco/css/correndo_esercizio_css_40.html
- TPSI/correndo_marco/css/correndo_esercizio_css_41.css
- TPSI/correndo_marco/css/correndo_esercizio_css_41.html
- TPSI/correndo_marco/css/correndo_esercizio_css_42.css
- TPSI/correndo_marco/css/correndo_esercizio_css_42.html
Consegna esercitazioni tpsi css da 39 a 42
> Consegna esercitazioni css da 39 a 42

- TPSI/pezzana_simone/css/pezzana_esercizio_css_39.css
- TPSI/pezzana_simone/css/pezzana_esercizio_css_39.html
- TPSI/pezzana_simone/css/pezzana_esercizio_css_40.css
- TPSI/pezzana_simone/css/pezzana_esercizio_css_40.html
- TPSI/pezzana_simone/css/pezzana_esercizio_css_41.css
- TPSI/pezzana_simone/css/pezzana_esercizio_css_41.html
- TPSI/pezzana_simone/css/pezzana_esercizio_css_42.css
- TPSI/pezzana_simone/css/pezzana_esercizio_css_42.html
consegno esercizi 39,40,41,42 di css.
> consegno esercitazioni tpsi 39,40,41,42 css.

- RETI/correndo_marco/codici/correndo_codice_hamming.c
- RETI/correndo_marco/codici/correndo_codice_parita.c
Consegna codici sulla parità e sulla lunghezza di hamming
> Consegna codici su parità e hamming
